version: "3.1"
services:
    db:
        image: mariadb:10.6
        container_name: db
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DBPASS}
            - MYSQL_DATABASE=RowanParkingApp
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}
        volumes:
            - ./docker-data/mysql:/var/lib/mysql
    parking:
        container_name: parking
        build: .
        image: parking:latest
        restart: unless-stopped
        ports:
            - 80:8080
        environment:
            - DBUSER=${DBUSER}
            - DBPASS=${DBPASS}
            - DBADDR=${DBADDR}
        depends_on:
            - db
