version: "3.1"
services:
    db:
        image: mariadb:10.6
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=parking
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        volumes:
            - ./docker-data/mysql:/var/lib/mysql
