version: "3.1"
services:
    db:
        image: mariadb:10.6
        restart: unless-stopped
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${DBPASS}
            - MYSQL_DATABASE=RowanParkingApp
            - MYSQL_USER=${DBUSER}
            - MYSQL_PASSWORD=${DBPASS}
        volumes:
            - ./docker-data/mysql:/var/lib/mysql
